
#ifndef _CODE_SIGNAL_TASKS_H_
#define _CODE_SIGNAL_TASKS_H_

#include <vector>
#include <unordered_map>
#include <map>
#include <climits>
#include <iterator>
#include <algorithm>
#include <string>

using namespace std::string_literals;

namespace codesignal_tasks {

/*
Given an integer n and an array a of length n, your task is to apply the following mutation to a:

Array a mutates into a new array b of length n.
For each i from 0 to n - 1, b[i] = a[i - 1] + a[i] + a[i + 1].
If some element in the sum a[i - 1] + a[i] + a[i + 1] does not exist, it should be set to 0. For example, b[0] should be equal to 0 + a[0] + a[1].
Example

For n = 5 and a = [4, 0, 1, -2, 3], the output should be mutateTheArray(n, a) = [4, 5, -1, 2, 1].

b[0] = 0 + a[0] + a[1] = 0 + 4 + 0 = 4
b[1] = a[0] + a[1] + a[2] = 4 + 0 + 1 = 5
b[2] = a[1] + a[2] + a[3] = 0 + 1 + (-2) = -1
b[3] = a[2] + a[3] + a[4] = 1 + (-2) + 3 = 2
b[4] = a[3] + a[4] + 0 = (-2) + 3 + 0 = 1
So, the resulting array after the mutation will be [4, 5, -1, 2, 1].

Input/Output

[execution time limit] 0.5 seconds (cpp)

[input] integer n

An integer representing the length of the given array.

Guaranteed constraints:
1 ≤ n ≤ 103.

[input] array.integer a

An array of integers that needs to be mutated.

Guaranteed constraints:
a.length = n,
-103 ≤ a[i] ≤ 103.

[output] array.integer

The resulting array after the mutation.

[C++] Syntax Tips

// Prints help message to the console
// Returns a string
string helloWorld(string name) {
    cout << "This prints to the console when you Run Tests" << endl;
    return "Hello, " + name;
}

*/
std::vector<int> mutateTheArray(int n, std::vector<int> a) {
    std::vector<int> b(n, 0);
    for(size_t i=0; i<n; ++i) {
        b[i] = a[i];
        if(i > 0) {
            b[i] += a[i-1];
        }
        if(i < (n-1)) {
            b[i] += a[i+1];
        }
    }
    
    return b;
}

/*
You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:

b[0] is equal to a[0];
b[1] is equal to the last element of a;
b[2] is equal to a[1];
b[3] is equal to the second-last element of a;
b[4] is equal to a[2];
b[5] is equal to the third-last element of a;
and so on.
Here is how this process works:



Your task is to determine whether the new array b is sorted in strictly ascending order or not.

Example

For a = [1, 3, 5, 6, 4, 2], the output should be alternatingSort(a) = true.

The new array b will look like [1, 2, 3, 4, 5, 6], which is in strictly ascending order, so the answer is true.

For a = [1, 4, 5, 6, 3], the output should be alternatingSort(a) = false.

The new array b will look like [1, 3, 4, 6, 5], which is not in strictly ascending order, so the answer is false.

Input/Output

[execution time limit] 0.5 seconds (cpp)

[input] array.integer a

The given array of integers.

Guaranteed constraints:
1 ≤ a.length ≤ 105,
-109 ≤ a[i] ≤ 109.

[output] boolean

A boolean representing whether the new array b will be sorted in strictly ascending order or not.

[C++] Syntax Tips

// Prints help message to the console
// Returns a string
string helloWorld(string name) {
    cout << "This prints to the console when you Run Tests" << endl;
    return "Hello, " + name;
}
*/
bool alternatingSort(std::vector<int> a) {
    // stricty sort => a[i-1] < a[i] < a[i+1]
    auto size = a.size();
    
    if(size < 2) {
        return true;
    }
 
    int lastVisitedValue = INT_MIN; 
    for(size_t i=0; i<size/2; ++i) {
        if(lastVisitedValue >= a[i]) {
            return false;
        }
        if(a[i] >= a[size-1-i]) {
            return false;
        }
        lastVisitedValue = a[size-1-i];
    }
    
    if(size % 2 == 1) { // control the element in the middle
        if(lastVisitedValue >= a[size/2]) {
            return false;
        }
    }
    
    return true;
}

/*
You are implementing your own programming language and you've decided to add support for merging strings. A typical merge function would take two strings s1 and s2, and return the lexicographically smallest result that can be obtained by placing the symbols of s2 between the symbols of s1 in such a way that maintains the relative order of the characters in each string.

For example, if s1 = "super" and s2 = "tower", the result should be merge(s1, s2) = "stouperwer".



You'd like to make your language more unique, so for your merge function, instead of comparing the characters in the usual lexicographical order, you'll compare them based on how many times they occur in their respective initial strings (fewer occurrences means the character is considered smaller). If the number of occurrences are equal, then the characters should be compared in the usual lexicographical way. If both number of occurences and characters are equal, you should take the characters from the first string to the result. Note that occurrences in the initial strings are compared - they do not change over the merge process.

Given two strings s1 and s2, return the result of the special merge function you are implementing.

Example

For s1 = "dce" and s2 = "cccbd", the output should be
mergeStrings(s1, s2) = "dcecccbd".
All symbols from s1 goes first, because all of them have only 1 occurrence in s1 and c has 3 occurrences in s2.



For s1 = "super" and s2 = "tower", the output should be
mergeStrings(s1, s2) = "stouperwer".
Because in both strings all symbols occur only 1 time, strings are merged as usual. You can find explanation for this example on the image in the description.

Input/Output

[execution time limit] 0.5 seconds (cpp)

[input] string s1

A string consisting only of lowercase English letters.

Guaranteed constraints:
1 ≤ s1.length ≤ 104.

[input] string s2

A string consisting only of lowercase English letters.

Guaranteed constraints:
1 ≤ s2.length ≤ 104.

[output] string

The string that results by merging s1 and s2 using your special merge function.

[C++] Syntax Tips

// Prints help message to the console
// Returns a string
string helloWorld(string name) {
    cout << "This prints to the console when you Run Tests" << endl;
    return "Hello, " + name;
}

*/
std::string mergeStrings(std::string s1, std::string s2) {
    auto sizeS1 = s1.size();
    auto sizeS2 = s2.size();
    
    std::unordered_map<char, int> mapS1;
    std::unordered_map<char, int> mapS2;
    
    // calculating the occurrences
    for(size_t i=0; i<sizeS1; ++i) {
        ++mapS1[s1[i]];
    }
    
    // calculating the occurrences
    for(size_t i=0; i<sizeS2; ++i) {
        ++mapS2[s2[i]];
    }
    
    std::string merged{""};
    auto i = 0;
    auto j = 0;
    while(i<sizeS1 && j<sizeS2) {
        auto s1C = s1[i];
        auto s2C = s2[j];
        
        // compare the occurrences of respective chars
        if(mapS1[s1C] < mapS2[s2C]) {
            merged.push_back(s1C);
            ++i;
        } else if(mapS1[s1C] > mapS2[s2C]) { // char at s2 occurs less!
            merged.push_back(s2C);
            ++j;
        } else {
            // compare the lexicographical order
            if(s1C < s2C) {
                merged.push_back(s1C);
                ++i;
            } else if(s1C > s2C) { // char at s2 is smaller
                merged.push_back(s2C);
                ++j;
            } else {
                merged.push_back(s1C);
                ++i;
            }
        }
    }
    
    // push back the leftovers
    while(i<sizeS1) {
        merged.push_back(s1[i]);
        ++i;
    }
    
    while(j<sizeS2) {
        merged.push_back(s2[j]);
        ++j;
    }

    return merged;
}

/*
You are given two arrays of integers a and b of the same length, and an integer k. We will be iterating through array a from left to right, and simultaneously through array b from right to left, and looking at pairs (x, y), where x is from a and y is from b. Such a pair is called tiny if the concatenation xy is strictly less than k.

Your task is to return the number of tiny pairs that you'll encounter during the simultaneous iteration through a and b.

Example

For a = [1, 2, 3], b = [1, 2, 3], and k = 31, the output should be
countTinyPairs(a, b, k) = 2.

We're considering the following pairs during iteration:

(1, 3). Their concatenation equals 13, which is less than 31, so the pair is tiny;
(2, 2). Their concatenation equals 22, which is less than 31, so the pair is tiny;
(3, 1). Their concatenation equals 31, which is not less than 31, so the pair is not tiny.
As you can see, there are 2 tiny pairs during the iteration, so the answer is 2.

For a = [16, 1, 4, 2, 14], b = [7, 11, 2, 0, 15], and k = 743, the output should be
countTinyPairs(a, b, k) = 4.

We're considering the following pairs during iteration:

(16, 15). Their concatenation equals 1615, which is greater than 743, so the pair is not tiny;
(1, 0). Their concatenation equals 10, which is less than 743, so the pair is tiny;
(4, 2). Their concatenation equals 42, which is less than 743, so the pair is tiny.
(2, 11). Their concatenation equals 211, which is less than 743, so the pair is tiny;
(14, 7). Their concatenation equals 147, which is less than 743, so the pair is tiny.
There are 4 tiny pairs during the iteration, so the answer is 4.

Input/Output

[execution time limit] 0.5 seconds (cpp)

[input] array.integer a

An array of non-negative integers.

Guaranteed constraints:
0 ≤ a.length ≤ 105,
0 ≤ a[i] ≤ 104.

[input] array.integer b

An array of non-negative integers.

Guaranteed constraints:
b.length = a.length,
0 ≤ b[i] ≤ 104.

[input] integer k

An integer to compare concatenated pairs with.

Guaranteed constraints:
0 ≤ k ≤ 109.

[output] integer

The number of tiny pairs during the iteration.

[C++] Syntax Tips

// Prints help message to the console
// Returns a string
string helloWorld(string name) {
    cout << "This prints to the console when you Run Tests" << endl;
    return "Hello, " + name;
}

*/
int multiplier(int x) {
    int multiply = 10;
    int divider = 10;
    
    x /= divider;
    while(x != 0) {
        multiply *= divider;
        x /= divider;
    }
    
    return multiply;
}

int countTinyPairs(std::vector<int> a, std::vector<int> b, int k) {
    // a & b same length
    // a: i=0 ....
    // b: j=n-1 ....
    // xy < k (strictly)
    // simultaneous iteration!
    auto counter = 0;
    auto size = a.size(); // b.size()
    for(size_t i=0; i<size; ++i) {
        auto x = a[i];
        auto y = b[size-1-i];
        auto multiply = multiplier(y);
        auto xy = x * multiply + y;
        if(xy < k) {
            ++counter;
        }
    }
    
    return counter;
}


/*
You are given an array of arrays a. Your task is to group the arrays a[i] by their mean values, so that arrays with equal mean values are in the same group, and arrays with different mean values are in different groups.

Each group should contain a set of indices (i, j, etc), such that the corresponding arrays (a[i], a[j], etc) all have the same mean. Return the set of groups as an array of arrays, where the indices within each group are sorted in ascending order, and the groups are sorted in ascending order of their minimum element.

Example

For

a = [[3, 3, 4, 2],
     [4, 4],
     [4, 0, 3, 3],
     [2, 3],
     [3, 3, 3]]
the output should be

meanGroups(a) = [[0, 4],
                 [1],
                 [2, 3]]
mean(a[0]) = (3 + 3 + 4 + 2) / 4 = 3;
mean(a[1]) = (4 + 4) / 2 = 4;
mean(a[2]) = (4 + 0 + 3 + 3) / 4 = 2.5;
mean(a[3]) = (2 + 3) / 2 = 2.5;
mean(a[4]) = (3 + 3 + 3) / 3 = 3.
There are three groups of means: those with mean 2.5, 3, and 4. And they form the following groups:

Arrays with indices 0 and 4 form a group with mean 3;
Array with index 1 forms a group with mean 4;
Arrays with indices 2 and 3 form a group with mean 2.5.
Note that neither

meanGroups(a) = [[0, 4],
                 [2, 3],
                 [1]]
nor

meanGroups(a) = [[0, 4],
                 [1],
                 [3, 2]]
will be considered as a correct answer:

In the first case, the minimal element in the array at index 2 is 1, and it is less then the minimal element in the array at index 1, which is 2.
In the second case, the array at index 2 is not sorted in ascending order.
For

a = [[-5, 2, 3],
     [0, 0],
     [0],
     [-100, 100]]
the output should be

meanGroups(a) = [[0, 1, 2, 3]]
The mean values of all of the arrays are 0, so all of them are in the same group.

Input/Output

[execution time limit] 0.5 seconds (cpp)

[input] array.array.integer a

An array of arrays of integers.

Guaranteed constraints:
1 ≤ a.length ≤ 100,
1 ≤ a[i].length ≤ 100,
-100 ≤ a[i][j] ≤ 100.

[output] array.array.integer

An array of arrays, representing the groups of indices.

[C++] Syntax Tips

// Prints help message to the console
// Returns a string
string helloWorld(string name) {
    cout << "This prints to the console when you Run Tests" << endl;
    return "Hello, " + name;
}
*/
std::vector<std::vector<int>> meanGroups(std::vector<std::vector<int>> a) {
    // group by mean
    // groups are sorted in ascending order!
    // indices within groups are sorted!
    std::vector<std::vector<int>> output;
    std::map<double, int> meanMap; // <mean, index>
    auto size = a.size();
    for(size_t i=0; i<size; ++i) {
        auto numOfElements = a[i].size();
        
        auto avg = 0.0;
        for(size_t j=0; j<numOfElements; ++j) {
            avg += a[i][j];
        }
        avg /= numOfElements;
        
        auto iter = meanMap.find(avg);
        if(iter == meanMap.end()) { // first time we add to the map
            meanMap[avg] = i;
            output.push_back({(int)i});
        } else { // already in the map!
            // we need to find the index!
            for(size_t j=0; j<output.size(); ++j) {
                if(iter->second == output[j][0]) {
                    output[j].push_back(i);
                    break;
                }
            }
        }
        
    }
    
    return output;
}

/*
You've created a new programming language, and now you've decided to add hashmap support to it. Actually you are quite disappointed that in common programming languages it's impossible to add a number to all hashmap keys, or all its values. So you've decided to take matters into your own hands and implement your own hashmap in your new language that has the following operations:

insert x y - insert an object with key x and value y.
get x - return the value of an object with key x.
addToKey x - add x to all keys in map.
addToValue y - add y to all values in map.
To test out your new hashmap, you have a list of queries in the form of two arrays: queryTypes contains the names of the methods to be called (eg: insert, get, etc), and queries contains the arguments for those methods (the x and y values).

Your task is to implement this hashmap, apply the given queries, and to find the sum of all the results for get operations.

Example

For queryType = ["insert", "insert", "addToValue", "addToKey", "get"] and query = [[1, 2], [2, 3], [2], [1], [3]], the output should be hashMap(queryType, query) = 5.

The hashmap looks like this after each query:

1 query: {1: 2}
2 query: {1: 2, 2: 3}
3 query: {1: 4, 2: 5}
4 query: {2: 4, 3: 5}
5 query: answer is 5
The result of the last get query for 3 is 5 in the resulting hashmap.



For queryType = ["insert", "addToValue", "get", "insert", "addToKey", "addToValue", "get"] and query = [[1, 2], [2], [1], [2, 3], [1], [-1], [3]], the output should be hashMap(queryType, query) = 6.

The hashmap looks like this after each query:

1 query: {1: 2}
2 query: {1: 4}
3 query: answer is 4
4 query: {1: 4, 2: 3}
5 query: {2: 4, 3: 3}
6 query: {2: 3, 3: 2}
7 query: answer is 2
The sum of the results for all the get queries is equal to 4 + 2 = 6.

Input/Output

[execution time limit] 0.5 seconds (cpp)

[input] array.string queryType

Array of query types. It is guaranteed that each queryType[i] is either "addToKey", "addToValue", "get", or "insert".

Guaranteed constraints:
1 ≤ queryType.length ≤ 105.

[input] array.array.integer query

Array of queries, where each query is represented either by two numbers for insert query or by one number for other queries. It is guaranteed that during all queries all keys and values are in the range [-109, 109].

Guaranteed constraints:
query.length = queryType.length,
1 ≤ query[i].length ≤ 2.

[output] integer64

The sum of the results for all get queries.

[C++] Syntax Tips

// Prints help message to the console
// Returns a string
string helloWorld(string name) {
    cout << "This prints to the console when you Run Tests" << endl;
    return "Hello, " + name;
}

*/
long long hashMap(std::vector<std::string> queryType, std::vector<std::vector<int>> query) {
    // queryType: names of the methods (insert, get, ...)
    // query: the arguments for the methods (x, y)
    // return sum of the results for all the "get" queries.
    auto size = queryType.size();
    std::unordered_map<long long, long long> myMap;
    
    long long keyAddition = 0;
    long long valueAddition = 0;
    
    long long sum = 0;
    for(size_t i=0; i<size; ++i) {
        auto function = queryType[i];
        auto args = query[i];
        if(function == "insert") { // insert <args[0], args[1]>
            myMap[args[0] - keyAddition] = args[1] - valueAddition;
        } else if(function == "get") { // getValue(args[0])
            auto value = myMap[args[0] - keyAddition];
            value += valueAddition;
            sum += value;
        } else if(function == "addToKey") { // add args[0] to all keys in the map!
            keyAddition += args[0];
        } else if(function == "addToValue") { // add args[0] to all values in the map!
            valueAddition += args[0];
        }
    }
    
    return sum;
}

int anagramConvert(int a) {
    int convertedAnagram = 0;
	std::vector<int> digitList;
    int modular = 10;
    while(a != 0) {
        auto digit = a % modular;
        digitList.push_back(digit);
        
        a -= digit;
        a /= modular;
    }
    
	std::sort(digitList.begin(), digitList.end());
	
	auto product = 1;
	for(auto const & iter : digitList) {
		convertedAnagram += iter*product;
		product *= 10;
	}
    
	return convertedAnagram;
}

/*
Sample tests:
15/15
Hidden tests:
14/15
Score:
287/300*/
long long digitAnagrams(std::vector<int> a) {
    long long counter = 0;  
	std::unordered_map<int, std::vector<int>> anagramMap;
    
    for(size_t i=0; i<a.size()-1; ++i) {
        auto converted = anagramConvert(a[i]);
		anagramMap[converted].push_back(a[i]);
    }
	
	for(auto const & iter : anagramMap) {
		auto anagramCount = iter.second.size();
		auto numOfAnagrams = (anagramCount*(anagramCount-1)) / 2;
		counter += numOfAnagrams;
	}
    
    return counter;
}

/*
Given an array of positive integers a, your task is to calculate the sum of every possible a[i] ∘ a[j], where a[i] ∘ a[j] is the concatenation of the string representations of a[i] and a[j] respectively.

Example

For a = [10, 2], the output should be concatenationsSum(a) = 1344.

a[0] ∘ a[0] = 10 ∘ 10 = 1010,
a[0] ∘ a[1] = 10 ∘ 2 = 102,
a[1] ∘ a[0] = 2 ∘ 10 = 210,
a[1] ∘ a[1] = 2 ∘ 2 = 22.
So the sum is equal to 1010 + 102 + 210 + 22 = 1344.

For a = [8], the output should be concatenationsSum(a) = 88.

There is only one number in a, and a[0] ∘ a[0] = 8 ∘ 8 = 88, so the answer is 88.

For a = [1, 2, 3], the output should be concatenationsSum(a) = 198.

a[0] ∘ a[0] = 1 ∘ 1 = 11,
a[0] ∘ a[1] = 1 ∘ 2 = 12,
a[0] ∘ a[2] = 1 ∘ 3 = 13,
a[1] ∘ a[0] = 2 ∘ 1 = 21,
a[1] ∘ a[1] = 2 ∘ 2 = 22,
a[1] ∘ a[2] = 2 ∘ 3 = 23,
a[2] ∘ a[0] = 3 ∘ 1 = 31,
a[2] ∘ a[1] = 3 ∘ 2 = 32,
a[2] ∘ a[2] = 3 ∘ 3 = 33.
The total result is 11 + 12 + 13 + 21 + 22 + 23 + 31 + 32 + 33 = 198.

Input/Output

[execution time limit] 0.5 seconds (cpp)

[input] array.integer a

A non-empty array of positive integers.

Guaranteed constraints:
1 ≤ a.length ≤ 105,
1 ≤ a[i] ≤ 106.

[output] integer64

The sum of all a[i] ∘ a[j]s. It's guaranteed that the answer is less than 253.

[C++] Syntax Tips

// Prints help message to the console
// Returns a string
string helloWorld(string name) {
    cout << "This prints to the console when you Run Tests" << endl;
    return "Hello, " + name;
}

*/
long long concatenationsSum(std::vector<int> a) {
    auto size = a.size();
    long long plainTotal = 0;
    for(auto const & iter : a) {
        plainTotal += iter;
    }

    long long total = 0;
    for(size_t i=0; i<size; ++i) {
        auto multiplied = plainTotal * multiplier(a[i]);
        auto subTotal = multiplied + (size*a[i]);
        
        total += subTotal;
    }
    
    return total;
}

#pragma region Operations

template<typename T>
void printArray(const std::vector<T> & tList) {
    std::cout << "Printing List: ";
    for(auto & iter : tList) std::cout << iter << " ";
    std::cout << std::endl;
}

void mutateTheArray_operations() {
    std::cout << std::endl << "=======================================" << std::endl;
    std::cout << "Starting Mutate The Array operations..." << std::endl;
    
    std::vector<int> list = {4, 0, 1, -2, 3};
    printArray(list);
    auto mutatedArray = mutateTheArray(5, list);
    std::cout << "Mutated Array" << std::endl;
    printArray(mutatedArray);

    std::cout << "Ending Mutate The Array operations..." << std::endl;
    std::cout << "=======================================" << std::endl;
}

void alternatingSort_operations() {
    std::cout << std::endl << "=======================================" << std::endl;
    std::cout << "Starting Alternating Sort operations..." << std::endl;
    
    std::vector<int> list = {1, 3, 5, 6, 4, 2};
    printArray(list);
    auto sorted = alternatingSort(list);
    std::cout << "Result: " << (sorted ? "array is sorted in strictly ascending order" : "array is NOT sorted in strictly ascending order") << std::endl;

    std::cout << "Ending Alternating Sort operations..." << std::endl;
    std::cout << "=======================================" << std::endl;
}

void countTinyPairs_operations() {
    std::cout << std::endl << "=======================================" << std::endl;
    std::cout << "Starting Count Tiny Pairs operations..." << std::endl;

    std::vector<int> a = {16, 1, 4, 2, 14};
    std::vector<int> b = {7, 11, 2, 0, 15};
    auto k=743;

    printArray(a);
    printArray(b);
    std::cout << "k: " << k << std::endl;
    
    auto numOfTinyPairs = countTinyPairs(a, b, k);
    std::cout << "Number of Tiny Pairs: " << numOfTinyPairs << std::endl;    

    std::cout << "Ending Count Tiny Pairs operations..." << std::endl;
    std::cout << "=======================================" << std::endl;
}

void meanGroups_operations() {
    std::cout << std::endl << "=======================================" << std::endl;
    std::cout << "Starting Mean Groups operations..." << std::endl;
    
    std::vector<std::vector<int>> a = {{3, 3, 4, 2}, {4, 4}, {4, 0, 3, 3}, {2, 3}, {3, 3, 3}};
    std::cout << "Input List:" << std::endl;
    for(auto const & iter : a) {
        printArray(iter);
    }
    auto meanGroupedList = meanGroups(a);
    std::cout << "Grouped List:" << std::endl;
    for(auto const & iter : meanGroupedList) {
        printArray(iter);
    }

    std::cout << "Ending Mean Groups operations..." << std::endl;
    std::cout << "=======================================" << std::endl;
}

void mergeStrings_operations() {
    std::cout << std::endl << "=======================================" << std::endl;
    std::cout << "Starting Merge Strings operations..." << std::endl;
    
    std::string s1("dce");
    std::string s2("cccbd");
    std::cout << "s1: " << s1 << " - s2: " << s2 << std::endl;
    auto merged = mergeStrings(s1, s2);
    std::cout << "Merged String: " << merged << std::endl;

    std::cout << "Ending Merge Strings operations..." << std::endl;
    std::cout << "=======================================" << std::endl;
}

void hashMap_operations() {
    std::cout << std::endl << "=======================================" << std::endl;
    std::cout << "Starting HashMap operations..." << std::endl;
    
    std::vector<std::string> queryTypeList = {"insert"s, "insert"s, "addToValue"s, "addToKey"s, "get"s};
    std::vector<std::vector<int>> queryList = {{1, 2}, {2, 3}, {2}, {1}, {3}};
    printArray(queryTypeList);
    auto sumOfGets = hashMap(queryTypeList, queryList);
    std::cout << "Sum of All Gets: " << sumOfGets << std::endl;

    std::cout << "Ending HashMap operations..." << std::endl;
    std::cout << "=======================================" << std::endl;
}

void digitAnagrams_operations() {
    std::cout << std::endl << "=======================================" << std::endl;
    std::cout << "Starting Digit Anagrams operations..." << std::endl;
    
    std::vector<int> list = {345, 657, 134, 879, 987, 534, 435};
    printArray(list);
    auto numOfAnagrams = digitAnagrams(list);
    std::cout << "Number of digit anagrams:" << numOfAnagrams << std::endl;

    std::cout << "Ending Digit Anagrams operations..." << std::endl;
    std::cout << "=======================================" << std::endl;
}

void concatenationsSum_operations() {
    std::cout << std::endl << "=======================================" << std::endl;
    std::cout << "Starting Concatenations Sum operations..." << std::endl;
    
    std::vector<int> a = {10, 2};
    printArray(a);
    auto concatSum = concatenationsSum(a);
    std::cout << "Sum of All Concatenations:" << concatSum << std::endl;

    a = {8};
    printArray(a);
    concatSum = concatenationsSum(a);
    std::cout << "Sum of All Concatenations:" << concatSum << std::endl;

    a = {1, 2, 3};
    printArray(a);
    concatSum = concatenationsSum(a);
    std::cout << "Sum of All Concatenations:" << concatSum << std::endl;

    std::cout << "Ending Concatenations Sum operations..." << std::endl;
    std::cout << "=======================================" << std::endl;
}

#pragma endregion Operations

void codesignal_operations() {
    mutateTheArray_operations();

    alternatingSort_operations();

    countTinyPairs_operations();

    mergeStrings_operations();

    meanGroups_operations();

    hashMap_operations();

    digitAnagrams_operations();

    concatenationsSum_operations();
}

} // codesignal_tasks

#endif // _CODE_SIGNAL_TASKS_H_